{{ if .Values.sealedSecrets.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-100"
  labels:
    app: "martian-bank-sealedsecret"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ./charts/sealed-secrets
    repoURL: https://github.com/mamonteiro-microops-pt/config_sealed_secrets.git
    targetRevision: HEAD
    helm:
      valueFiles:
        - ./values.yaml
        - ./environments/{{.Values.environment}}/values.yaml
  syncPolicy:
    # automated:
    #   prune: true
    #   selfHeal: true
    syncOptions:
      - CreateNamespace=true
{{ end }}